### ISSUE TITLE
Execute API not working

### ISSUE THREAD

**Issue by NickHeap2** [pattisoj/my-hero-academia-api#8]
I think these need to be the other way round otherwise your / route is being used even for /characters
https://github.com/pattisoj/my-hero-academia-api/blob/72e7ccdbec2c86b046b40c6addbe6e66bdea373f/app.js#L30-L31

This means the test execute of the api brings back the swagger docs.
![image](https://user-images.githubusercontent.com/42422453/193588128-0422c90b-b4d1-4478-b643-165b4e36ca74.png)

**Comment by pattisoj** [comment]
Thank you! When I changed the docs to utilise swagger I removed and index router so overlooked this, I will fix it now.
